// Initialising variables needed
var shopping_cart_pressed = 0;
var data = {"total":0,"rows":[]};
var totalCost = 0;
var margin = 0;

$(document).ready(function() {

  // Selecting grid
  'use strict';
  $('#cartcontent').datagrid({
    singleSelect:true
  });

  // Checking if local storage exists and if it has item called cart
  if(localStorage && localStorage.getItem('cart')){

    // Declare variables using data in the local storage
    var cart = localStorage.getItem('cart');
    totalCost = parseInt(localStorage.getItem('totalCost'));
    var totalItems = parseInt(localStorage.getItem('totalItems'), 10);

    // Display the data on the website
    $(".shopping_cart_cost").text("£" + Math.round(totalCost * 100) / 100);
    $(".cart_items_count").text(totalItems);
    $(".cart__count").text(totalItems);

    // Parse JSON data from local storage so it can be display in the cart and display it in carts
    var items = JSON.parse(cart);
    $('#cartcontent').datagrid('loadData', items);
    data = items;
    }

  // If button of the cart is pressed, cart will be showed
  $( ".cart" ).click(function(event) {
    // It wasn't pressed before, show it
    if(shopping_cart_pressed == 0){
    event.preventDefault();
    $(".shopping_cart").css("visibility", "visible");
    $(".basket_icon").css("visibility", "visible");
    shopping_cart_pressed = 1;
  }else if(shopping_cart_pressed == 1){
    // It was pressed before, hide it
    $(".shopping_cart").css("visibility", "hidden");
    $(".basket_icon").css("visibility", "hidden");
    shopping_cart_pressed = 0;
  }
  });

  // If buy button was pressed in the cart, show message
  $( ".cart_buy_button" ).click(function(event) {
    event.preventDefault();
    if(totalCost != 0){
    // If total cost is not zero (1 or more items selected) show message 1
    $( ".overlay" ).fadeIn( "slow",
    function() {
      $( ".overlay" ).delay(5000).fadeOut("slow");
    });
  }else{
    // If total cost is zero (no items selected) show message 2
    $( ".overlay2" ).fadeIn( "slow",
    function() {
      $( ".overlay2" ).delay(5000).fadeOut("slow");
    });
  }
  });

  // Clears the local storage and refreshers the page
  $( ".cart_reset_button" ).click(function(event) {
    localStorage.clear();
    location.reload();
  });

  // Gets the name and the price of the item and adds it to the cart as well as updates local storage with it too
  $( ".action--buy" ).click(function(event, source) {
    var name = $(this).attr("name_data");
    var price = $(this).attr("price_data");
    addProduct(name, parseFloat(price));
    var data_string = JSON.stringify(data);
    localStorage.setItem("cart", data_string);
    localStorage.setItem("totalCost", totalCost);
		var cartItems = parseInt($('.cart__count').text(), 10);
    localStorage.setItem("totalItems", cartItems+1);
  });

  // Removes datagrid on start as its autogenerated and not needed
  if ($('.datagrid-view1')[0]) {
      $('.datagrid-view1').delay(200).remove();
  };

});


// Function which adds the product to the cart
function addProduct(name,price){
  'use strict';
  function add(){
    for(var i=0; i<data.total; i++){
      var row = data.rows[i];
      if (row.name === name){
        // If the name is the same of the product, add one to the quantity instead of adding another product
        row.quantity += 1;
        return;
      }
    }
    // Add one to total and push the changes to the data
    data.total += 1;
    data.rows.push({
      name:name,
      quantity:1,
      price:price
    });
  }
  add();
  // Updates the total costs on the website
  totalCost += parseInt(price, 10);
  // load data grid from jquery ui
  $('#cartcontent').datagrid('loadData', data);
  // Updates totals in the html
  $(".shopping_cart_cost").text("£" + Math.round(totalCost * 100) / 100);
}
